[package]
name = "dotr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.1", features = ["derive", "unstable-doc"] }
directories = "5.0.1"
git2 = "0.17.2"
glob = "0.3.1"
itertools = "0.10.5"
thiserror = "1.0.40"

